name: All Tests

on:
  push:
    branches: [ master, 'ci/*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies and run backend test 
      run: | 
        cd frontend
        npm ci
        npm test
    
  test-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies and run backend test 
      env: 
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_API_AUTH_TOKEN: ${{ secrets.TWILIO_API_AUTH_TOKEN }}
        TWILIO_API_KEY_SECRET: ${{ secrets.TWILIO_API_KEY_SECRET }}
        TWILIO_API_KEY_SID: ${{ secrets.TWILIO_API_KEY_SID }}
      run: | 
        cd services/roomservice/
        npm ci
        npm test

